---

name: Action self-test

on:
  pull_request:
    branches: [ '*' ]

jobs:
  test-action:
    name: Enforce convention commit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Test the action locally
        uses: matmar10/pr-conventional-commit@1.1.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
